### ISSUE TITLE
Always respond with CORS headers on the Stripe charge endpoint

### ISSUE THREAD

**Issue by exarkun** [PrivateStorageio/PaymentServer#50]
When a response doesn't include CORS headers, it is unavailable to JavaScript in the browser.

Unfortunately, the way CORS is implemented now, it seems like error responses often result in CORS headers being left out of the response.  One specific example of this is that if the response body to `/v1/stripe/charge` fails to parse as a `Charge` then the response is:

```
HTTP/2 500 
date: Wed, 08 Apr 2020 12:04:39 GMT
server: Warp/3.2.28
```

**Comment by hacklschorsch** [comment]
> Unfortunately, the way CORS is implemented now, it seems like error responses often result in CORS headers being left out of the response.

This makes the response code and response text unavailable to the cliend-side error handling code I have added here: https://whetstone.private.storage/privatestorage/privatestorageweb/-/merge_requests/91

![Screenshot of Chrome developer tools showing a 500 response which we can't access from Javascript](https://user-images.githubusercontent.com/454605/155637133-6f2e303a-cfda-486e-8c5b-0ef903586dfe.png "500 error, no CORS")

As it is now, that will just leave us with a generic error message without details, which is better than what we had before.

Still, I thought this should be resolved?
Is it not?

**Comment by exarkun** [comment]
It looks like I didn't fix anything in #87 - I just added automated tests that demonstrate it already works correctly.  It sounds like you observed it not working correctly so I wonder what case you find that I didn't.

Do you have an example of a request that provokes this behavior?

**Comment by hacklschorsch** [comment]
#111 is fixing this for the voucher-already-paid case and... _maybe_ also for other payment related cases?

2655f77's commit message says:

> This change adds an exception handler to the `payForVoucher` call that
transforms all `PaymentError` exceptions into `Left e` values which `charge`
is already handling.  `throwError` will eventually throw a `ServerError` with
correct details filled in for these.

**Comment by exarkun** [comment]
Oh yea.  2655f77 was probably meant to fix this, I forgot the ticket link.  I don't think it fixed the other case though because the other case already used `throwError` to throw a `ServerError` and didn't have a `throwIO` in its codepath... (I think).
